name: Checking deb versions

on:
  schedule:
   - cron: '0 * * * *'  
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests packaging

    - name: Run version checker
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }} 
      run: python check_deb_versions.py
